### ISSUE TITLE
Error: Cannot find module '/node_modules/html-pdf-chrome/dist/src/index.js'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by adamreisnz** [westy92/html-pdf-chrome#300]
Getting this error since upgrading to 0.7.0.
Working fine with 0.6.1.

PS: This is with Node 16.1.0

**Comment by westy92** [comment]
Thank you for the report! It should be fixed in [v0.7.1](https://github.com/westy92/html-pdf-chrome/releases/tag/v0.7.1).

**Comment by adamreisnz** [comment]
Cheers thanks
